# Generated by Django 5.1.7 on 2025-04-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=122)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.TextField(max_length=122)),
                ('number_of_people', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
